### ISSUE TITLE
Default Date Should Be Today

### ISSUE THREAD

**Issue by UGamer** [UGamer/UGame-Launcher#99]
Change the default date in the date picker when in the entry window be today's date.

**Comment by hotz07** [comment]
Just add the initialization of the DatePicker in your constructor:

       public MainWindow()
        {
            InitializeComponent();

            datePicker1.SelectedDate = DateTime.Now;
        }

**Comment by UGamer** [comment]
Thanks!

Implemented for beta 5.10.2
